package com.zzptc.sky.dbphoneguard.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zzptc.sky.dbphoneguard.entity.ContactInfo;
import com.zzptc.sky.dbphoneguard.entity.FunctionTable;
import com.zzptc.sky.dbphoneguard.entity.Mobile;

import com.zzptc.sky.dbphoneguard.dao.ContactInfoDao;
import com.zzptc.sky.dbphoneguard.dao.FunctionTableDao;
import com.zzptc.sky.dbphoneguard.dao.MobileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactInfoDaoConfig;
    private final DaoConfig functionTableDaoConfig;
    private final DaoConfig mobileDaoConfig;

    private final ContactInfoDao contactInfoDao;
    private final FunctionTableDao functionTableDao;
    private final MobileDao mobileDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactInfoDaoConfig = daoConfigMap.get(ContactInfoDao.class).clone();
        contactInfoDaoConfig.initIdentityScope(type);

        functionTableDaoConfig = daoConfigMap.get(FunctionTableDao.class).clone();
        functionTableDaoConfig.initIdentityScope(type);

        mobileDaoConfig = daoConfigMap.get(MobileDao.class).clone();
        mobileDaoConfig.initIdentityScope(type);

        contactInfoDao = new ContactInfoDao(contactInfoDaoConfig, this);
        functionTableDao = new FunctionTableDao(functionTableDaoConfig, this);
        mobileDao = new MobileDao(mobileDaoConfig, this);

        registerDao(ContactInfo.class, contactInfoDao);
        registerDao(FunctionTable.class, functionTableDao);
        registerDao(Mobile.class, mobileDao);
    }
    
    public void clear() {
        contactInfoDaoConfig.clearIdentityScope();
        functionTableDaoConfig.clearIdentityScope();
        mobileDaoConfig.clearIdentityScope();
    }

    public ContactInfoDao getContactInfoDao() {
        return contactInfoDao;
    }

    public FunctionTableDao getFunctionTableDao() {
        return functionTableDao;
    }

    public MobileDao getMobileDao() {
        return mobileDao;
    }

}
